#server port no
#server:
#  port: 8081
  
#Application name  
spring:
  application:
    name: WELCOME-API

#Admin server url to register the api    
  boot:
    admin:
      client:
        url: http://localhost:1111/
 
 #Actuator management endpoints to include, here * means all       
management:
  endpoints:
    web:
      exposure:
        include: '*'
